version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: axelpilop-heimdall_1
      APP_PORT: 80

heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${APP_DATA_DIR}/data:/config
#    ports:
#      - 80:80
#      - 443:443
    restart: unless-stopped