services:
  app_proxy:
    environment:
      APP_HOST: server
      APP_PORT: 1924

  server:
    build:
      context: https://github.com/raccommode/LorcanaLocalManager.git
      dockerfile_inline: |
        FROM node:18-alpine
        WORKDIR /app
        COPY package*.json ./
        RUN npm install --only=production
        COPY . .
        RUN mkdir -p /app/data
        HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
          CMD curl -f http://localhost:1924/ || exit 1
        ENV PORT=1924
        CMD ["npm", "start"]
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PORT=1924
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
