services:
  app_proxy:
    environment:
      APP_HOST: raccommode-lorcanalocalmanager_server_1
      APP_PORT: 1923

  server:
    build: https://github.com/raccommode/LorcanaLocalManager.git
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    ports:
      - "1923:1923"