services:
  app_proxy:
    environment:
      APP_HOST: server
      APP_PORT: 8080
    ports:
      - 8729:8080

  server:
    build: https://github.com/raccommode/LorcanaLocalManager.git
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
