services:
  app_proxy:
    environment:
      APP_HOST: server
      APP_PORT: 1923

  server:
    build: https://github.com/raccommode/LorcanaLocalManager.git
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PORT=1923
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
