services:
  app_proxy:
    environment:
      APP_HOST: raccommode-lorcanalocalmanager_server_1
      APP_PORT: 1923

  server:
    build:
      context: https://github.com/raccommode/LorcanaLocalManager.git
      dockerfile_inline: |
        FROM node:18-alpine
        WORKDIR /app
        COPY package*.json ./
        RUN npm install --only=production
        COPY . .
        RUN mkdir -p /app/data
        EXPOSE 1923
        HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
          CMD curl -f http://localhost:1923/ || exit 1
        ENV PORT=1923
        CMD ["npm", "start"]
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PORT=1923
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    ports:
      - "1923:1923"