version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: sparkles-mastodon_1
      APP_PORT: 3000
    
  server:
    image: tootsuite/mastodon
    user: "1000:1000"
    init: true