version: "3.9"

services:

  app_proxy:
    environment:
      APP_HOST: serge
      APP_PORT: 8008

serge:
    restart: on-failure
    build: 
      context: .
      dockerfile: Dockerfile
      target: release
    volumes:
      - datadb:${APP_DATA_DIR}/db
      - weights:${APP_DATA_DIR}/weights
      - /etc/localtime:/etc/localtime:ro 

volumes:
  datadb:
  weights: